# Generated by Django 3.2.5 on 2021-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0002_alter_python_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='work_category',
            field=models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Architecture', 'Architecture')], default='IT', max_length=20),
        ),
        migrations.AlterField(
            model_name='python',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
