# Generated by Django 3.2.5 on 2021-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_usersubscriptionplan_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='max_job_posts',
            field=models.IntegerField(default=0),
        ),
    ]
