# Generated by Django 3.2.5 on 2021-08-08 18:19

import ckeditor.fields
import cloudinary.models
import utils.validate_image_extention
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Моля въведете поне 2 символа!')])),
                ('description', ckeditor.fields.RichTextField()),
                ('city', models.CharField(default='София', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Моля въведете поне 2 символа!')])),
                ('salary', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_type', models.CharField(choices=[('на час', 'на час'), ('на месец', 'на месец'), ('по договаряне', 'по договаряне')], default='на час', max_length=50)),
                ('work_category', models.CharField(choices=[('ИТ', 'ИТ'), ('Финанси', 'Финанси'), ('Архитектука', 'Архитектука'), ('Инженерство', 'Инженерство'), ('Продажби, Маркетинг, ПР', 'Продажби, Маркетинг, ПР'), ('Сигурност', 'Сигурност')], default='IT', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[utils.validate_image_extention.validate_img_extensions], verbose_name='image')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='job_posts', to='profiles.ProfileModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
