# Generated by Django 3.2.5 on 2021-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='work_category',
            field=models.CharField(choices=[('ИТ', 'ИТ'), ('Финанси', 'Финанси'), ('Архитектура', 'Архитектура'), ('Инженерство', 'Инженерство'), ('Продажби, Маркетинг, ПР', 'Продажби, Маркетинг, ПР'), ('Сигурност', 'Сигурност')], default='IT', max_length=50),
        ),
    ]
