# Generated by Django 3.2.5 on 2021-08-15 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobmodel_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='last_modified',
            field=models.DateTimeField(default=datetime.time(18, 29, 28, 648416)),
        ),
    ]
