# Generated by Django 3.2.5 on 2021-08-15 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobmodel_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 18, 44, 56, 882418)),
        ),
    ]
