# Generated by Django 3.2.5 on 2021-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobmodel_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='work_type',
            field=models.CharField(choices=[('Търся Хора', 'Търся Хора'), ('Предлагам Услуга', 'Предлагам Услуга')], default='Търся Хора', max_length=50),
        ),
    ]
