# Generated by Django 3.2.5 on 2021-09-06 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobmodel_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
