# Generated by Django 3.2.5 on 2021-09-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobmodel_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='date_joined',
            new_name='date_posted',
        ),
    ]
