# Generated by Django 3.2.5 on 2021-09-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_rename_date_joined_jobmodel_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
