# Generated by Django 3.2.5 on 2021-07-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_auth', '0003_auto_20210717_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileForm',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profile_auth.appuser')),
            ],
        ),
    ]
