# Generated by Django 3.2.5 on 2021-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbaseusermodel',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
