# Generated by Django 3.2.5 on 2021-08-08 18:19

import cloudinary.models
import utils.validate_image_extention
import utils.validate_urls
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Моля въведете поне 2 символа!')])),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Моля въведете поне 2 символа!')])),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, validators=[utils.validate_image_extention.validate_img_extensions], verbose_name='image')),
                ('profession', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Моля въведете поне 2 символа!')])),
                ('website_url', models.URLField(blank=True, max_length=255, null=True, validators=[utils.validate_urls.is_string_an_url])),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True, validators=[utils.validate_urls.is_string_an_url])),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, validators=[utils.validate_urls.is_string_an_url])),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True, validators=[utils.validate_urls.is_string_an_url])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='job_auth.appbaseusermodel')),
            ],
        ),
    ]
