# Generated by Django 3.2.5 on 2021-09-29 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profession',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Моля въведете поне 2 символа!')]),
        ),
    ]
